version: '3.8'
services:
  eureka-server:
    image: eureka #nombre de la imagen que hemos creado
    restart: always
    container_name: eureka
    ports:
      - '8761:8761'
    networks:
      - 'dockermicroservices-network'
  product-service:
    image: product-service #nombre de la imagen que hemos creado
    restart: always
    container_name: product-service:1.0
    ports:
      - '8002:8002'
    networks:
      - 'dockermicroservices-network'
  customer-service:
    image: customer-service #nombre de la imagen que hemos creado
    restart: always
    container_name: customer-service:1.0
    ports:
      - '8003:8003'
    networks:
      - 'dockermicroservices-network'
  shopping-service:
    image: shopping-service #nombre de la imagen que hemos creado
    restart: always
    container_name: shopping-service:1.0
    ports:
      - '8004:8004'
    networks:
      - 'dockermicroservices-network'    
networks:
  dockermicroservices-network: