version: '3.8'
services:
  config-server:
    image: hugojesusmr/config-server:1.0 #nombre de la imagen que hemos creado
    restart: always
    container_name: config-server
    ports:
      - '8001:8001'
    networks:
      - 'dockermicroservices-network'
  registry-service:
    image: hugojesusmr/registry-service:1.0 #nombre de la imagen que hemos creado
    restart: always
    container_name: registry-service
    ports:
      - '8761:8761'
    networks:
      - 'dockermicroservices-network'
  product-service:
    image: hugojesusmr/product-service:1.0 #nombre de la imagen que hemos creado
    restart: always
    container_name: product-service
    ports:
      - '8002:8002'
    networks:
      - 'dockermicroservices-network'
  customer-service:
    image: hugojesusmr/customer-service:1.0 #nombre de la imagen que hemos creado
    restart: always
    container_name: customer-service
    ports:
      - '8003:8003'
    networks:
      - 'dockermicroservices-network'
  shopping-service:
    image: hugojesusmr/shopping-service:1.0 #nombre de la imagen que hemos creado
    restart: always
    container_name: shopping-service
    ports:
      - '8004:8004'
    networks:
      - 'dockermicroservices-network'    
networks:
  dockermicroservices-network: